ALTER TABLE users
    ADD COLUMN salutation VARCHAR(10) NOT NULL DEFAULT 'Others',
    ADD COLUMN first_name VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN last_name VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN phone_number VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN date_of_birth DATE NOT NULL DEFAULT '1997-10-10';